# Activate with: --spring.profiles.active=prod
spring.datasource.url=jdbc:postgresql://localhost:5432/catalog
spring.datasource.username=postgres
spring.datasource.password=1@2B3z49

spring.jpa.hibernate.ddl-auto=update
